services:
  database_postgres:
    container_name: postgres-stream
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "0.0.0.0:5432:5432" # TODO: review this when putting on home server
    environment:
      POSTGRES_USER: streamer
      POSTGRES_PASSWORD: streamerWP14!
      POSTGRES_DB: mediadb 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamer -d mediadb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: aistor-server
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console (Web UI) port
    env_file:
      - .env # Load MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      # Data storage
      - ${MINIO_PATH}/data:/mnt/data
      # License file requirement
      - ${MINIO_PATH}/minio.license:/minio.license
      # Certs for TLS
      - ${MINIO_PATH}/certs:/etc/minio/certs
    command: >
      minio server /mnt/data 
      --console-address ":9001" 
      --license /minio.license
    restart: unless-stopped
  
  ms-backend:
    container_name: ms-backend
    build: . 
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ./app_data:/app/data
    depends_on:
      database_postgres:
        condition: service_healthy
