"""add cast credits

Revision ID: 02d1d2ef2524
Revises: 7a19ee2882b9
Create Date: 2026-05-04 14:45:57.113447

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02d1d2ef2524'
down_revision: Union[str, Sequence[str], None] = '7a19ee2882b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'people',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tmdb_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('profile_path', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table(
        'credits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('movie_id', sa.Integer(), nullable=True),
        sa.Column('show_id', sa.Integer(), nullable=True),
        sa.Column('character', sa.String(length=255), nullable=True),
        sa.Column('cast_order', sa.Integer(), nullable=True),
        sa.Column('episode_count', sa.Integer(), nullable=True),
        sa.CheckConstraint(
            '(movie_id IS NULL AND show_id IS NOT NULL) OR (movie_id IS NOT NULL AND show_id IS NULL)',
            name='chk_credit_movie_or_show',
        ),
        sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['show_id'], ['tv_shows.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # Partial indexes: a credit row has either a movie_id or a show_id, never
    # both. Excluding the NULL half keeps each index lean and skips the rows
    # the corresponding query path will never touch.
    op.create_index(
        'ix_credits_movie_order',
        'credits',
        ['movie_id', 'cast_order'],
        unique=False,
        postgresql_where=sa.text('movie_id IS NOT NULL'),
    )
    op.create_index(
        op.f('ix_credits_person_id'), 'credits', ['person_id'], unique=False
    )
    op.create_index(
        'ix_credits_show_episode_count',
        'credits',
        ['show_id', 'episode_count'],
        unique=False,
        postgresql_where=sa.text('show_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credits_show_episode_count', table_name='credits')
    op.drop_index(op.f('ix_credits_person_id'), table_name='credits')
    op.drop_index('ix_credits_movie_order', table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
