"""Add availability boolean for files, movies, shows, episodes

Revision ID: 39d2d221ec7b
Revises: 199dd99e0bc2
Create Date: 2026-03-28 21:11:51.064778

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39d2d221ec7b'
down_revision: Union[str, Sequence[str], None] = '199dd99e0bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'episodes',
        sa.Column(
            'is_available', sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    op.add_column(
        'media_files',
        sa.Column(
            'is_available', sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    op.add_column(
        'movies',
        sa.Column(
            'is_available', sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    op.add_column(
        'tv_shows',
        sa.Column(
            'is_available', sa.Boolean(), server_default=sa.true(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_shows', 'is_available')
    op.drop_column('movies', 'is_available')
    op.drop_column('media_files', 'is_available')
    op.drop_column('episodes', 'is_available')
    # ### end Alembic commands ###
