"""Add indexes and cascading deletes to media and user models

Revision ID: 3bca5f0364f3
Revises: 39d2d221ec7b
Create Date: 2026-03-31 18:58:23.083629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bca5f0364f3'
down_revision: Union[str, Sequence[str], None] = '39d2d221ec7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    op.drop_constraint(op.f('episodes_season_id_fkey'), 'episodes', type_='foreignkey')
    op.create_foreign_key(None, 'episodes', 'seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_media_files_episode_id'), 'media_files', ['episode_id'], unique=False)
    op.create_index(op.f('ix_media_files_movie_id'), 'media_files', ['movie_id'], unique=False)
    op.drop_constraint(op.f('media_files_episode_id_fkey'), 'media_files', type_='foreignkey')
    op.drop_constraint(op.f('media_files_movie_id_fkey'), 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media_files', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_seasons_show_id'), 'seasons', ['show_id'], unique=False)
    op.drop_constraint(op.f('seasons_show_id_fkey'), 'seasons', type_='foreignkey')
    op.create_foreign_key(None, 'seasons', 'tv_shows', ['show_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_show_progress_last_watched_episode_id'), 'user_show_progress', ['last_watched_episode_id'], unique=False)
    op.create_index(op.f('ix_user_show_progress_last_watched_season_id'), 'user_show_progress', ['last_watched_season_id'], unique=False)
    op.create_index(op.f('ix_user_show_progress_user_id'), 'user_show_progress', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_show_progress_last_watched_season_id_fkey'), 'user_show_progress', type_='foreignkey')
    op.drop_constraint(op.f('user_show_progress_last_watched_episode_id_fkey'), 'user_show_progress', type_='foreignkey')
    op.drop_constraint(op.f('user_show_progress_show_id_fkey'), 'user_show_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_show_progress', 'seasons', ['last_watched_season_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_show_progress', 'episodes', ['last_watched_episode_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_show_progress', 'tv_shows', ['show_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_watch_progress_media_file_id'), 'watch_progress', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    op.drop_constraint(op.f('watch_progress_media_file_id_fkey'), 'watch_progress', type_='foreignkey')
    op.create_foreign_key(None, 'watch_progress', 'media_files', ['media_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_progress', type_='foreignkey')
    op.create_foreign_key(op.f('watch_progress_media_file_id_fkey'), 'watch_progress', 'media_files', ['media_file_id'], ['id'])
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_media_file_id'), table_name='watch_progress')
    op.drop_constraint(None, 'user_show_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_show_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_show_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_show_progress_show_id_fkey'), 'user_show_progress', 'tv_shows', ['show_id'], ['id'])
    op.create_foreign_key(op.f('user_show_progress_last_watched_episode_id_fkey'), 'user_show_progress', 'episodes', ['last_watched_episode_id'], ['id'])
    op.create_foreign_key(op.f('user_show_progress_last_watched_season_id_fkey'), 'user_show_progress', 'seasons', ['last_watched_season_id'], ['id'])
    op.drop_index(op.f('ix_user_show_progress_user_id'), table_name='user_show_progress')
    op.drop_index(op.f('ix_user_show_progress_last_watched_season_id'), table_name='user_show_progress')
    op.drop_index(op.f('ix_user_show_progress_last_watched_episode_id'), table_name='user_show_progress')
    op.drop_constraint(None, 'seasons', type_='foreignkey')
    op.create_foreign_key(op.f('seasons_show_id_fkey'), 'seasons', 'tv_shows', ['show_id'], ['id'])
    op.drop_index(op.f('ix_seasons_show_id'), table_name='seasons')
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.create_foreign_key(op.f('media_files_movie_id_fkey'), 'media_files', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('media_files_episode_id_fkey'), 'media_files', 'episodes', ['episode_id'], ['id'])
    op.drop_index(op.f('ix_media_files_movie_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_episode_id'), table_name='media_files')
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.create_foreign_key(op.f('episodes_season_id_fkey'), 'episodes', 'seasons', ['season_id'], ['id'])
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    # ### end Alembic commands ###
