"""add deleted_at to media_files

Revision ID: 7a19ee2882b9
Revises: bea3a393250a
Create Date: 2026-05-01 19:14:17.189439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a19ee2882b9'
down_revision: Union[str, Sequence[str], None] = 'bea3a393250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'deleted_at')
    # ### end Alembic commands ###
