"""Add has_ever_completed to watch_progress

Revision ID: aad116581d78
Revises: 3bca5f0364f3
Create Date: 2026-03-31 23:24:12.986113

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aad116581d78'
down_revision: Union[str, Sequence[str], None] = '3bca5f0364f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'watch_progress',
        sa.Column(
            'has_ever_completed',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )

    op.alter_column('watch_progress', 'has_ever_completed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'has_ever_completed')
    # ### end Alembic commands ###
