"""replace omdb columns with imdb_ratings table

Revision ID: bea3a393250a
Revises: bfccd01fdd70
Create Date: 2026-04-29 18:48:40.815542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea3a393250a'
down_revision: Union[str, Sequence[str], None] = 'bfccd01fdd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdb_ratings',
    sa.Column('tconst', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.drop_column('episodes', 'imdb_votes')
    op.drop_column('episodes', 'imdb_rating')
    op.drop_column('movies', 'imdb_votes')
    op.drop_column('movies', 'imdb_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('imdb_votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('imdb_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('imdb_votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('imdb_ratings')
    # ### end Alembic commands ###
