"""Add imdb id and ratings to movies and episodes

Revision ID: bfccd01fdd70
Revises: c86afed01877
Create Date: 2026-04-28 21:41:29.162500

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bfccd01fdd70'
down_revision: Union[str, Sequence[str], None] = 'c86afed01877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('imdb_id', sa.String(length=20), nullable=True))
    op.add_column('episodes', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('episodes', sa.Column('imdb_votes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_episodes_imdb_id'), 'episodes', ['imdb_id'], unique=False)
    op.add_column('movies', sa.Column('imdb_id', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('imdb_votes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_column('movies', 'imdb_votes')
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'imdb_id')
    op.drop_index(op.f('ix_episodes_imdb_id'), table_name='episodes')
    op.drop_column('episodes', 'imdb_votes')
    op.drop_column('episodes', 'imdb_rating')
    op.drop_column('episodes', 'imdb_id')
    # ### end Alembic commands ###
