"""Add runtime to movies and episodes

Revision ID: c86afed01877
Revises: aa5b0bfbe8b9
Create Date: 2026-04-27 22:24:16.458199

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c86afed01877'
down_revision: Union[str, Sequence[str], None] = 'aa5b0bfbe8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'runtime')
    op.drop_column('episodes', 'runtime')
    # ### end Alembic commands ###
